aws_region           = "sa-east-1"
iac                  = "Terraform"
environment          = "HML"
project		     = "covid-0-brasil"
equipe		     = "Eng_platform"
principal            = "s3.amazonaws.com"
bucket_name          = "covid-0-brasil"
